Repository COSC-481W-Dodo/dodo-android, pull requests merged in 2022-11, with the labels that each got.

#83 feat: Flesh out ViewTags states, add check functionality | #71
  app/src/main/java/com/dodo/flashcards/data/repository/FlashcardRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/angledAccentDrawBehind.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewDelegate.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadErrorTags.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadingTags.kt
Labels: sprint 2

#84 feat: Add navigation from View Tags to View Cards with argument passing | #72
  app/build.gradle
  app/src/main/java/com/dodo/flashcards/presentation/MainActivity.kt
  app/src/main/java/com/dodo/flashcards/presentation/MainModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/MainNavHost.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
  app/src/main/java/com/dodo/flashcards/util/Screen.kt
Labels: sprint 2

#85 feat: Implement tags received from Firestore | #71
  app/build.gradle
  app/src/main/java/com/dodo/flashcards/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/data/repository/FlashcardRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/di/AppModule.kt
Labels: sprint 2

#86 style: Minor style improvements to View Tags Screen | #72
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadErrorTags.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
Labels: sprint 2

#87 feat: Crude implementation of loading flashcard from database | #72
  app/src/main/java/com/dodo/flashcards/data/repository/FlashcardRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/ScreenBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/FillMaxSizeWIthBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/fillMaxSizeWithBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/previews/ViewCardsScreenPreview/PreviewCardFlip.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlippableFlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
Labels: sprint 2

#88 feat: Add forward / previous temp buttons with func | #72
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
Labels: sprint 2

#90 feat: Add swiping control, implement previous button into card | #72
  app/build.gradle
  app/google-services-old.json
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/AngledDrawBehindModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/BounceScaleModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/FillSizeWithBackgroundModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/FlipCardModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/SwipeModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/fillMaxSizeWithBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/previews/ViewCardsScreenPreview/PreviewCardFlip.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/DummyCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlippableFlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
Labels: sprint 2

#91 feat: Clean up errors associated with View Tags & View Cards | #72
  app/src/main/java/com/dodo/flashcards/presentation/common/ScreenBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/DummyCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlippableFlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoadError.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewDelegate.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
Labels: sprint 2

#93 style: Add scaffold and validation to view tags/cards | #71
  app/src/main/java/com/dodo/flashcards/presentation/common/AppScaffold.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/ScreenBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewDelegate.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/subscreen/LoadedTags.kt
Labels: sprint 2

#95 fix: Fix the text alignment of cards to be centered.
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/DummyCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlippableFlashCard.kt
Labels: bug, sprint 2

#100 refactor: Rewrite swipeable modifier, add Quizlet features | #97
  app/build.gradle
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/Flip.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/FlipCardModifier_OLD.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/SwipeModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/previews/ViewCardsScreenPreview/PreviewCardFlip.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/DummyCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlippableFlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/CardSwipeModifiers.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/SwipeableCardState.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoadError.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
Labels: sprint 3

#101 feat: Add filter tags feature | #98
  app/src/main/java/com/dodo/flashcards/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/data/repository/FlashcardRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/domain/models/AuthRepository.kt
  app/src/main/java/com/dodo/flashcards/domain/models/FlashcardRepository.kt
  app/src/main/java/com/dodo/flashcards/domain/usecases/authentication/GetUserIdUseCase.kt
  app/src/main/java/com/dodo/flashcards/domain/usecases/flashcards/GetUserTagsUseCase.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/AppScaffold.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewDelegate.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewTagsScreen/ViewTagsViewModel.kt
Labels: sprint 3

#102 feat: Rewrite flippable modifier | #97
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/dodo/flashcards/data/repository/FlashcardRepositoryImpl.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/ScreenBackground.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/Flip.kt
  app/src/main/java/com/dodo/flashcards/presentation/common/commonModifiers/ReversedModifier.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/flip/CardFlipModifiers.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/flip/FlippableCardState.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/swipe/CardSwipeModifiers.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/swipe/SwipeableCardState.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
Labels: sprint 3

#103 Prevent multiple click bug | #97
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/FlashCard.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsModels.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsScreen.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/ViewCardsViewModel.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/flip/CardFlipModifiers.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/flip/FlippableCardState.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/modifiers/swipe/CardSwipeModifiers.kt
  app/src/main/java/com/dodo/flashcards/presentation/viewCardsScreen/subscreen/CardsLoaded.kt
Labels: sprint 3
